

export const colHelperTimesheetMines = [
{ type: 'text', width: '100', title: 'Unit No' },
{ type: 'text', width: '100', title: 'Product Model' },
{ type: 'text', width: '200', title: 'Description' },
{ type: 'text', width: '70', title: 'Owner' },
{ type: 'text', width: '120', title: 'Production Date' },
{ type: 'text', width: '65', title: 'Shift' },
{ type: 'text', width: '100', title: 'Operator ID' },
{ type: 'text', width: '160', title: 'Operator Name' },
{ type: 'text', width: '80', title: 'SMU Start' },
{ type: 'text', width: '80', title: 'SMU Finish' },
{ type: 'text', width: '80', title: 'HM' },
{ type: 'text', width: '230', title: 'Activity' },
{ type: 'text', width: '140', title: 'Start Time' },
{ type: 'text', width: '140', title: 'End Time' },
{ type: 'text', width: '100', title: 'Duration' },
{ type: 'text', width: '120', title: 'Convert Duration' },
{ type: 'text', width: '100', title: 'BD Number' },
{ type: 'text', width: '150', title: 'From Equipment' },
{ type: 'text', width: '150', title: 'Material' },
{ type: 'text', width: '100', title: 'Mat Group' },
{ type: 'text', width: '100', title: 'Distance' },
{ type: 'text', width: '150', title: 'Loading Location' },
{ type: 'text', width: '150', title: 'Dumping Location' },
{ type: 'text', width: '100', title: 'Trip' },
{ type: 'text', width: '100', title: 'BCM' },
{ type: 'text', width: '150', title: 'Notes' },
{ type: 'text', width: '120', title: 'Cutoff Status' },
{ type: 'text', width: '100', title: 'LOC' }
]
