export const NavigateUrl = {
    HOME: '/',
    DETAIL_PAGE: '/details',
    // COAL_HAULING_TABLE_DETAIL: '/coalhauling-dataentry-detail',
    // COAL_HAULING_DATA_ENTRY_FORM: '/coalhauling-dataentry-form',
    // TIME_ENTRY_MAIN_TABLE: '/time-entry-from-collector',
    // TIME_ENTRY_DETAIL_TABLE: '/time-entry-detail/:date',
    // TIME_ENTRY_SUPPORT_FORM: '/time-entry-support-form',
    // TIME_ENTRY_DIGGER_FORM: '/time-entry-digger-form',
    // TIME_ENTRY_HAULER_FORM: '/time-entry-hauler-form',
    // HOUR_METER_DATA_ENTRY: '/hour-meter-dataentry',
    // BREAKDOWN_DATA_ENTRY: '/breakdown-dataentry',
    // FLEET_UNIT_DATA_ENTRY: '/fleet-unit-dataentry',
    // WEATHER_DATA_ENTRY: '/weather-dataentry',
}